# Generated by Django 4.0.2 on 2022-08-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('o', 'open'), ('c', 'close')], max_length=30)),
                ('priority', models.CharField(choices=[('l', 'low'), ('m', 'medium'), ('c', 'close')], max_length=30)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
